version: "3.9"

services:
  backend:
    build: ./Backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: luzifer715
      DATABASE_NAME: agriculture
    command: ["./wait-for-it.sh", "db:3306", "--", "npm", "start"]
    networks:
      - backend-network

  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: http://backend:3001
    networks:
      - backend-network

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: luzifer715
      MYSQL_DATABASE: agriculture
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  db_data:
    driver: local
